#!/usr/bin/env node
/**
 * BZZAI Helper - TUI Menu for toggling Zai API
 * No external dependencies required (gum)
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

// ANSI colors for terminal
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
};

// Config paths
const ZAI_ROOT = process.env.ZAI_ROOT || path.join(os.homedir(), '.zai');
const ENV_FILE = path.join(ZAI_ROOT, 'env.sh');
const CLAUDE_SETTINGS = path.join(os.homedir(), '.claude', 'settings.json');

// Ensure .zai directory exists
if (!fs.existsSync(ZAI_ROOT)) {
  fs.mkdirSync(ZAI_ROOT, { recursive: true });
}

// Create example env if not exists
if (!fs.existsSync(ENV_FILE)) {
  const example = `# Zai API Configuration
# Edit this file with your API key

ZAI_AUTH_TOKEN="your-api-key-here"
ZAI_BASE_URL="https://api.z.ai/api/anthropic"
ZAI_TIMEOUT_MS="3000000"
ZAI_HAIKU_MODEL="glm-4.5-air"
ZAI_SONNET_MODEL="glm-5-turbo"
ZAI_OPUS_MODEL="glm-5.1"
ZAI_DEBUG="0"
`;
  fs.writeFileSync(ENV_FILE, example);
}

// Parse env.sh file
function loadEnv() {
  const content = fs.readFileSync(ENV_FILE, 'utf8');
  const env = {};
  content.split('\n').forEach(line => {
    const match = line.match(/^(\w+)="(.*)"$/);
    if (match) {
      env[match[1]] = match[2];
    }
  });
  // Defaults for users with older env.sh that lacks model vars
  if (!env.ZAI_HAIKU_MODEL) env.ZAI_HAIKU_MODEL = 'glm-4.5-air';
  if (!env.ZAI_SONNET_MODEL) env.ZAI_SONNET_MODEL = 'glm-5-turbo';
  if (!env.ZAI_OPUS_MODEL) env.ZAI_OPUS_MODEL = 'glm-5.1';
  return env;
}

// Save env.sh file
function saveEnv(env) {
  const content = `# Zai API Configuration
# Auto-generated by bzzai-helper

ZAI_AUTH_TOKEN="${env.ZAI_AUTH_TOKEN}"
ZAI_BASE_URL="${env.ZAI_BASE_URL}"
ZAI_TIMEOUT_MS="${env.ZAI_TIMEOUT_MS}"
ZAI_HAIKU_MODEL="${env.ZAI_HAIKU_MODEL}"
ZAI_SONNET_MODEL="${env.ZAI_SONNET_MODEL}"
ZAI_OPUS_MODEL="${env.ZAI_OPUS_MODEL}"
ZAI_DEBUG="0"
`;
  fs.writeFileSync(ENV_FILE, content);
}

// Get current status from Claude settings
function getStatus() {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    return { enabled: false };
  }
  try {
    const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
    const settings = JSON.parse(content);
    const hasToken = settings.env?.ANTHROPIC_AUTH_TOKEN;
    if (hasToken) {
      return {
        enabled: true,
        url: settings.env.ANTHROPIC_BASE_URL || 'unknown',
      };
    }
  } catch (e) {
    // Ignore parse errors
  }
  return { enabled: false };
}

// Enable Zai
function enableZai(env) {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    console.log(`${colors.red}Error: Claude settings not found at ${CLAUDE_SETTINGS}${colors.reset}`);
    return false;
  }
  const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
  const settings = JSON.parse(content);
  settings.env = settings.env || {};
  settings.env.ANTHROPIC_AUTH_TOKEN = env.ZAI_AUTH_TOKEN;
  settings.env.ANTHROPIC_BASE_URL = env.ZAI_BASE_URL;
  settings.env.API_TIMEOUT_MS = env.ZAI_TIMEOUT_MS;
  settings.env.ANTHROPIC_DEFAULT_HAIKU_MODEL = env.ZAI_HAIKU_MODEL;
  settings.env.ANTHROPIC_DEFAULT_SONNET_MODEL = env.ZAI_SONNET_MODEL;
  settings.env.ANTHROPIC_DEFAULT_OPUS_MODEL = env.ZAI_OPUS_MODEL;
  fs.writeFileSync(CLAUDE_SETTINGS, JSON.stringify(settings, null, 2));
  return true;
}

// Disable Zai
function disableZai() {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    console.log(`${colors.red}Error: Claude settings not found at ${CLAUDE_SETTINGS}${colors.reset}`);
    return false;
  }
  console.log(`${colors.yellow}Tip: Run /compact or /clear in Claude Code before switching to avoid signature errors${colors.reset}`);
  const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
  const settings = JSON.parse(content);
  settings.env = settings.env || {};
  settings.env.ANTHROPIC_AUTH_TOKEN = "";
  settings.env.ANTHROPIC_BASE_URL = "";
  settings.env.API_TIMEOUT_MS = "";
  settings.env.ANTHROPIC_DEFAULT_HAIKU_MODEL = "";
  settings.env.ANTHROPIC_DEFAULT_SONNET_MODEL = "";
  settings.env.ANTHROPIC_DEFAULT_OPUS_MODEL = "";
  fs.writeFileSync(CLAUDE_SETTINGS, JSON.stringify(settings, null, 2));
  return true;
}

// Setup keypress events once
const readline = require('readline');
let keypressInitialized = false;

function initKeypress() {
  if (!keypressInitialized && process.stdin.isTTY) {
    readline.emitKeypressEvents(process.stdin);
    keypressInitialized = true;
  }
}

// Arrow key navigation menu
function showMenu() {
  const env = loadEnv();

  const options = [
    { label: 'Enable Zai', desc: 'Switch to Zai API' },
    { label: 'Disable Zai', desc: 'Switch back to Anthropic' },
    { label: 'Check Status', desc: 'Show current status' },
    { label: 'Edit Config', desc: 'Edit API config' },
    { label: 'Quit', desc: 'Exit' },
  ];

  let selectedIndex = 0;
  let active = true;

  function render() {
    const status = getStatus();
    console.clear();
    console.log('');
    console.log(`${colors.magenta}${colors.bright}    ╔═════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.magenta}${colors.bright}    ║     BZZAI Toggle Menu           ║${colors.reset}`);
    console.log(`${colors.magenta}${colors.bright}    ╚═════════════════════════════════╝${colors.reset}`);
    console.log('');
    const statusText = status.enabled
      ? `${colors.green}[ON] Zai ENABLED${colors.reset}`
      : `${colors.white}[OFF] Zai DISABLED${colors.reset}`;
    console.log(`${colors.dim}    Status:${colors.reset} ${statusText}`);
    console.log('');
    console.log(`${colors.dim}    ─────────────────────────────────────${colors.reset}`);
    console.log('');

    options.forEach((opt, i) => {
      const prefix = i === selectedIndex ? `${colors.cyan}  > ` : '    ';
      const label = i === selectedIndex
        ? `${colors.bright}${colors.cyan}${opt.label}${colors.reset}`
        : `${colors.white}${opt.label}${colors.reset}`;
      const desc = `${colors.dim}${opt.desc}${colors.reset}`;
      console.log(`${prefix}${label}  ${desc}`);
    });

    console.log('');
    console.log(`${colors.dim}    ─────────────────────────────────────${colors.reset}`);
    console.log('');
    console.log(`${colors.dim}    ↑↓ Navigate  Enter Select  q Quit${colors.reset}`);
  }

  function handleSelect() {
    active = false;
    process.stdin.removeListener('keypress', onKeypress);

    switch (selectedIndex) {
      case 0: // Enable Zai
        if (enableZai(env)) {
          showMessage(`${colors.green}✓ Zai enabled${colors.reset}`, showMenu);
        } else {
          showMenu();
        }
        break;
      case 1: // Disable Zai
        if (disableZai()) {
          const msg = `${colors.green}✓ Zai disabled (using Anthropic default)${colors.reset}\n\n${colors.yellow}Tip: Run /compact or /clear before using to avoid signature errors${colors.reset}`;
          showMessage(msg, showMenu);
        } else {
          showMenu();
        }
        break;
      case 2: // Check Status
        const status = getStatus();
        let msg;
        if (status.enabled) {
          msg = `${colors.cyan}Status:${colors.reset}\n  ${colors.green}[ON] Zai ENABLED${colors.reset}\n  ${colors.dim}URL: ${status.url}${colors.reset}`;
        } else {
          msg = `${colors.cyan}Status:${colors.reset}\n  ${colors.white}[OFF] Zai DISABLED (default Anthropic)${colors.reset}`;
        }
        showMessage(msg, showMenu);
        break;
      case 3: // Edit Config
        if (process.stdin.isTTY) {
          process.stdin.setRawMode(false);
        }
        editConfig(env);
        break;
      case 4: // Quit
        if (process.stdin.isTTY) {
          process.stdin.setRawMode(false);
        }
        console.clear();
        console.log('');
        console.log(`${colors.dim}Goodbye!${colors.reset}`);
        console.log('');
        process.exit(0);
        break;
    }
  }

  function onKeypress(str, key) {
    if (!active || !key) return;

    if (key.name === 'up') {
      selectedIndex = (selectedIndex - 1 + options.length) % options.length;
      render();
    } else if (key.name === 'down') {
      selectedIndex = (selectedIndex + 1) % options.length;
      render();
    } else if (key.name === 'return') {
      handleSelect();
    } else if (key.name === 'q' || (key.ctrl && key.name === 'c')) {
      active = false;
      if (process.stdin.isTTY) {
        process.stdin.setRawMode(false);
      }
      console.clear();
      console.log('');
      console.log(`${colors.dim}Goodbye!${colors.reset}`);
      console.log('');
      process.exit(0);
    }
  }

  // Initialize
  initKeypress();
  if (process.stdin.isTTY) {
    process.stdin.setRawMode(true);
  }
  process.stdin.resume();
  render();
  process.stdin.on('keypress', onKeypress);
}

function showMessage(msg, callback) {
  console.clear();
  console.log('');
  console.log(msg);
  console.log('');
  console.log(`${colors.dim}Press any key to continue...${colors.reset}`);

  if (process.stdin.isTTY) {
    process.stdin.setRawMode(true);
  }
  process.stdin.resume();
  process.stdin.once('keypress', () => {
    callback();
  });
}

// Edit config with arrow key navigation
function editConfig(env) {
  const options = [
    { label: 'Edit Token', desc: `${'****' + env.ZAI_AUTH_TOKEN.slice(-4)}` },
    { label: 'Edit URL', desc: env.ZAI_BASE_URL },
    { label: 'Edit Timeout', desc: `${env.ZAI_TIMEOUT_MS}ms` },
    { label: 'Edit Haiku Model', desc: env.ZAI_HAIKU_MODEL },
    { label: 'Edit Sonnet Model', desc: env.ZAI_SONNET_MODEL },
    { label: 'Edit Opus Model', desc: env.ZAI_OPUS_MODEL },
    { label: 'Save', desc: 'Save changes' },
    { label: 'Back', desc: 'Return to main menu' },
    { label: 'Exit', desc: 'Quit program' },
  ];

  let selectedIndex = 0;
  let active = true;

  function render() {
    console.clear();
    console.log('');
    console.log(`${colors.cyan}${colors.bright}    ╔═════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.cyan}${colors.bright}    ║     Edit Configuration          ║${colors.reset}`);
    console.log(`${colors.cyan}${colors.bright}    ╚═════════════════════════════════╝${colors.reset}`);
    console.log('');

    // Update descriptions with current values
    options[0].desc = `${'****' + env.ZAI_AUTH_TOKEN.slice(-4)}`;
    options[1].desc = env.ZAI_BASE_URL;
    options[2].desc = `${env.ZAI_TIMEOUT_MS}ms`;
    options[3].desc = env.ZAI_HAIKU_MODEL;
    options[4].desc = env.ZAI_SONNET_MODEL;
    options[5].desc = env.ZAI_OPUS_MODEL;

    options.forEach((opt, i) => {
      const prefix = i === selectedIndex ? `${colors.cyan}  > ` : '    ';
      const label = i === selectedIndex
        ? `${colors.bright}${colors.cyan}${opt.label}${colors.reset}`
        : `${colors.white}${opt.label}${colors.reset}`;
      const desc = `${colors.dim}${opt.desc}${colors.reset}`;
      console.log(`${prefix}${label}  ${desc}`);
    });

    console.log('');
    console.log(`${colors.dim}    ─────────────────────────────────────${colors.reset}`);
    console.log('');
    console.log(`${colors.dim}    ↑↓ Navigate  Enter Select  q Quit${colors.reset}`);
  }

  function promptInput(label, currentValue, callback) {
    active = false;
    process.stdin.removeListener('keypress', onKeypress);
    if (process.stdin.isTTY) {
      process.stdin.setRawMode(false);
    }

    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    console.clear();
    console.log('');
    console.log(`${colors.cyan}${label}${colors.reset}`);
    console.log(`${colors.dim}Current: ${currentValue}${colors.reset}`);
    console.log(`${colors.dim}Press Enter to keep current value${colors.reset}`);
    console.log('');

    rl.question(`${colors.cyan}New value: ${colors.reset}`, (answer) => {
      rl.close();
      callback(answer.trim() || null);
    });
  }

  function handleSelect() {
    switch (selectedIndex) {
      case 0: // Edit Token
        promptInput('Edit Token', '****' + env.ZAI_AUTH_TOKEN.slice(-4), (val) => {
          if (val) env.ZAI_AUTH_TOKEN = val;
          restartMenu();
        });
        break;
      case 1: // Edit URL
        promptInput('Edit Base URL', env.ZAI_BASE_URL, (val) => {
          if (val) env.ZAI_BASE_URL = val;
          restartMenu();
        });
        break;
      case 2: // Edit Timeout
        promptInput('Edit Timeout (ms)', env.ZAI_TIMEOUT_MS, (val) => {
          if (val) env.ZAI_TIMEOUT_MS = val;
          restartMenu();
        });
        break;
      case 3: // Edit Haiku Model
        promptInput('Edit Haiku Model', env.ZAI_HAIKU_MODEL, (val) => {
          if (val) env.ZAI_HAIKU_MODEL = val;
          restartMenu();
        });
        break;
      case 4: // Edit Sonnet Model
        promptInput('Edit Sonnet Model', env.ZAI_SONNET_MODEL, (val) => {
          if (val) env.ZAI_SONNET_MODEL = val;
          restartMenu();
        });
        break;
      case 5: // Edit Opus Model
        promptInput('Edit Opus Model', env.ZAI_OPUS_MODEL, (val) => {
          if (val) env.ZAI_OPUS_MODEL = val;
          restartMenu();
        });
        break;
      case 6: // Save
        active = false;
        process.stdin.removeListener('keypress', onKeypress);
        saveEnv(env);
        showMessage(`${colors.green}✓ Config saved${colors.reset}`, showMenu);
        break;
      case 7: // Back
        active = false;
        process.stdin.removeListener('keypress', onKeypress);
        showMenu();
        break;
      case 8: // Exit
        active = false;
        if (process.stdin.isTTY) {
          process.stdin.setRawMode(false);
        }
        console.clear();
        console.log('');
        console.log(`${colors.dim}Goodbye!${colors.reset}`);
        console.log('');
        process.exit(0);
        break;
    }
  }

  function restartMenu() {
    active = true;
    initKeypress();
    if (process.stdin.isTTY) {
      process.stdin.setRawMode(true);
    }
    process.stdin.resume();
    render();
    process.stdin.on('keypress', onKeypress);
  }

  function onKeypress(str, key) {
    if (!active || !key) return;

    if (key.name === 'up') {
      selectedIndex = (selectedIndex - 1 + options.length) % options.length;
      render();
    } else if (key.name === 'down') {
      selectedIndex = (selectedIndex + 1) % options.length;
      render();
    } else if (key.name === 'return') {
      handleSelect();
    } else if (key.name === 'q' || (key.ctrl && key.name === 'c')) {
      active = false;
      if (process.stdin.isTTY) {
        process.stdin.setRawMode(false);
      }
      console.clear();
      console.log('');
      console.log(`${colors.dim}Goodbye!${colors.reset}`);
      console.log('');
      process.exit(0);
    }
  }

  // Initialize
  initKeypress();
  if (process.stdin.isTTY) {
    process.stdin.setRawMode(true);
  }
  process.stdin.resume();
  render();
  process.stdin.on('keypress', onKeypress);
}

// CLI mode
function cliMode(args) {
  const env = loadEnv();
  const cmd = args[0];

  switch (cmd) {
    case 'on':
      if (enableZai(env)) {
        console.log(`${colors.green}✓ Zai enabled${colors.reset}`);
      }
      break;
    case 'off':
      if (disableZai()) {
        console.log(`${colors.green}✓ Zai disabled (using Anthropic default)${colors.reset}`);
      }
      break;
    case 'status':
      const status = getStatus();
      if (status.enabled) {
        console.log(`${colors.green}[ON] Zai ENABLED${colors.reset}`);
        console.log(`${colors.dim}URL: ${status.url}${colors.reset}`);
      } else {
        console.log(`${colors.white}[OFF] Zai DISABLED (default Anthropic)${colors.reset}`);
      }
      break;
    default:
      console.log(`Usage: bzzai [on|off|status|menu]`);
      console.log(`  npx bzzai-helper        - Open TUI menu`);
      console.log(`  npx bzzai-helper on     - Enable Zai`);
      console.log(`  npx bzzai-helper off    - Disable Zai`);
      console.log(`  npx bzzai-helper status - Check status`);
      process.exit(1);
  }
}

// Main entry
const args = process.argv.slice(2);
if (args.length > 0 && args[0] !== 'menu') {
  cliMode(args);
} else {
  showMenu();
}
