#!/bin/bash
# Zai TUI Menu powered by Gum
# Usage: ./menu.sh or source it

ZAI_DIR="${ZAI_DIR:-$HOME/DataStore/me/claude/zai}"
ZAI_ENV_TEMPLATE="$ZAI_DIR/env.sh"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

# Load env values
if [[ -f "$ZAI_ENV_TEMPLATE" ]]; then
  source "$ZAI_ENV_TEMPLATE"
fi

# zai-on / zai-off / zai-status come from the shared wrappers, which delegate to
# index.js — one implementation for the settings.json logic (no duplicated jq).
source "$ZAI_DIR/lib/toggle.sh"

# Get current status (enabled decision delegated to node; URL just read for display)
get_status() {
  if zai-status | grep -q '\[ON\]'; then
    local url=$(jq -r '.env.ANTHROPIC_BASE_URL // "not set"' "$CLAUDE_SETTINGS" 2>/dev/null)
    echo "🟢 Zai: ENABLED"
    echo "   Base URL: $url"
  else
    echo "⚪ Zai: DISABLED (default Anthropic)"
  fi
}

# Edit config via TUI input
edit-config() {
  # Show current values
  gum style --foreground 240 --margin "1 0" "Current values:"

  gum style --foreground 212 "  Token:    ${ZAI_AUTH_TOKEN:0:20}..."
  gum style --foreground 212 "  Base URL: $ZAI_BASE_URL"
  gum style --foreground 212 "  Timeout:  $ZAI_TIMEOUT_MS ms"
  gum style --foreground 212 "  Haiku:    ${ZAI_HAIKU_MODEL:-glm-4.5-air}"
  gum style --foreground 212 "  Sonnet:   ${ZAI_SONNET_MODEL:-glm-5.2[1m]}"
  gum style --foreground 212 "  Opus:     ${ZAI_OPUS_MODEL:-glm-5.2[1m]}"
  echo ""

  # Input new values
  local new_token=$(gum input --value "$ZAI_AUTH_TOKEN" --placeholder "API Auth Token" --width 50 --header "Token")
  local new_url=$(gum input --value "$ZAI_BASE_URL" --placeholder "Base URL" --width 50 --header "Base URL")
  local new_timeout=$(gum input --value "$ZAI_TIMEOUT_MS" --placeholder "Timeout (ms)" --width 20 --header "Timeout")
  local new_haiku=$(gum input --value "${ZAI_HAIKU_MODEL:-glm-4.5-air}" --placeholder "Haiku model" --width 30 --header "Haiku Model")
  local new_sonnet=$(gum input --value "${ZAI_SONNET_MODEL:-glm-5.2[1m]}" --placeholder "Sonnet model" --width 30 --header "Sonnet Model")
  local new_opus=$(gum input --value "${ZAI_OPUS_MODEL:-glm-5.2[1m]}" --placeholder "Opus model" --width 30 --header "Opus Model")

  # Confirm
  echo ""
  gum confirm "Save changes?" || return 0

  # Write to env.sh
  cat > "$ZAI_ENV_TEMPLATE" <<EOF
# Zai API Configuration
# Auto-generated by zai-menu

ZAI_AUTH_TOKEN="$new_token"
ZAI_BASE_URL="$new_url"
ZAI_TIMEOUT_MS="$new_timeout"
ZAI_HAIKU_MODEL="$new_haiku"
ZAI_SONNET_MODEL="$new_sonnet"
ZAI_OPUS_MODEL="$new_opus"

# Debug mode (1=on, 0=off)
ZAI_DEBUG="\${ZAI_DEBUG:-0}"
EOF

  # Reload
  source "$ZAI_ENV_TEMPLATE"

  gum style --foreground 46 "✓ Config saved"
  gum spin --spinner dot --title "Waiting..." -- sleep 1
}

# Main menu
zai-menu() {
  while true; do
    # Clear screen
    clear

    # Header
    gum style \
      --foreground 212 --border-foreground 212 --border double \
      --align center --width 40 --margin "1 2" \
      "BZZAI Toggle Menu"

    # Status
    gum style --foreground 240 --margin "0 2" "$(get_status)"

    # Menu
    choice=$(gum choose \
      --cursor "▶ " \
      --header "$(gum style --foreground 240 'Select action')" \
      --margin "1 2" \
      "Enable Zai" \
      "Disable Zai" \
      "Check Status" \
      "Edit Config" \
      "Exit")

    case "$choice" in
      "Enable Zai")
        zai-on
        gum style --foreground 46 "✓ Zai enabled"
        gum spin --spinner dot --title "Waiting..." -- sleep 1
        ;;
      "Disable Zai")
        zai-off
        gum style --foreground 46 "✓ Zai disabled (default Anthropic)"
        gum spin --spinner dot --title "Waiting..." -- sleep 1
        ;;
      "Check Status")
        gum style --foreground 215 "$(get_status)"
        echo ""
        gum confirm "Continue?" || return 0
        ;;
      "Edit Config")
        edit-config
        ;;
      "Exit")
        return 0
        ;;
    esac
  done
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  zai-menu
fi
